=LET(
    yr_2010, 40179,
    yr_2035, 49673,
    ye_dt,   DATE(2025,12,31),
    isNzNum, LAMBDA(num_val, AND(LEN(num_val)>0, ISNUMBER(num_val), num_val>0)),
    isDate,  LAMBDA(date_val, AND(isNzNum(date_val), date_val>=yr_2010, date_val<=yr_2035)),
    mkary,   LAMBDA(date_val, desc, HSTACK(date_val, desc)),
    days_to_add,    INDIRECT("O"&ROW()),
    allow,          INDIRECT("P"&ROW()),
    crit_dt_type,   INDIRECT("Q"&ROW()),
    sale_type,      INDIRECT("X"&ROW()),
    ship_dt,        INDIRECT("AD"&ROW()),
    etd_dt,         INDIRECT("AE"&ROW()),
    inv_dt,         INDIRECT("AF"&ROW()),
    eta_dest,       INDIRECT("AG"&ROW()),
    title_dt,       INDIRECT("AK"&ROW()),
    wbl_date,       INDIRECT("AL"&ROW()),
    paid_date,      INDIRECT("AJ"&ROW()),
    rting_port_eta, INDIRECT("AN"&ROW()),
    tran_port_eta,  INDIRECT("AP"&ROW()),
    est_tran_days,  INDIRECT("AQ"&ROW()),
    price,          INDIRECT("BA"&ROW()),
    base_adj,       days_to_add+allow,
    valid_hdrs, AND(
        INDIRECT("O1")="No. of Days to Add",
        INDIRECT("P1")="Allowance", 
        INDIRECT("Q1")="Critical Date",
        INDIRECT("X1")="Destination",
        INDIRECT("AD1")="Ship Date",
        INDIRECT("AE1")="ETD",
        INDIRECT("AF1")="Date Doc Sent",
        INDIRECT("AG1")="ETA Destination",
        INDIRECT("AK1")="Title Doc Date",
        INDIRECT("AL1")="WBL Date",
        INDIRECT("AJ1")="Paid Date",
        INDIRECT("AN1")="Routing Port ETA",
        INDIRECT("AP1")="Transit Port ETA",
        INDIRECT("AQ1")="Est Transit to RP",
        INDIRECT("BA1")="Price"
    ),
    hasPaidDate,   isDate(paid_date),
    hasShipDate,   isDate(ship_dt),
    hasETDDate,    isDate(etd_dt),
    hasInvDate,    isDate(inv_dt),
    hasETADest,    isDate(eta_dest),
    hasTitleDate,  isDate(title_dt),
    hasWBLDate,    isDate(wbl_date),
    hasRtingETA,   isDate(rting_port_eta),
    hasTransitETA, isDate(tran_port_eta),
    hasPrice,      isNzNum(price),
    sale_type_Dm,     sale_type="Domestic",
    sale_type_Ex,     sale_type="Export", 
    sale_type_Fresh,  sale_type="Fresh Sales",
    crit_dt_Inv,      crit_dt_type="Invoice Date",
    crit_dt_DDS,      crit_dt_type="Date Docs Sent",
    crit_dt_ETA_K,    crit_dt_type="ETA Klaipeda",
    crit_dt_ETD,      crit_dt_type="ETD",
    crit_dt_Title,    crit_dt_type="Title Transfer Date",
    crit_dt_Deliv,    crit_dt_type="Delivery Date",
    crit_dt_RtingPrt, crit_dt_type="Routing Port ETA",
    crit_dt_CheckSO,  crit_dt_type="Check SO",
    rting_port_is_YE,    AND(hasRtingETA, rting_port_eta=ye_dt),
    rting_port_not_YE,   AND(hasRtingETA, NOT(rting_port_is_YE)),
    YE_and_transit,      AND(rting_port_is_YE, hasTransitETA),
    no_title_has_rting,  AND(NOT(hasTitleDate), hasRtingETA),
    no_transit_has_ship, AND(NOT(hasTransitETA), hasShipDate),
    f_invoice_base,      inv_dt+base_adj,
    f_title_transf_base, title_dt+base_adj,
    f_delivery_base,     wbl_date+base_adj,
    f_rting_port_base,   rting_port_eta+base_adj+5,
    f_transit_eta_base,  tran_port_eta+est_tran_days+base_adj+5,
    f_rting_port_ext,    rting_port_eta+base_adj+7,
    f_ship_fallback,     ship_dt+base_adj+30,
    f_fresh_ship,        ship_dt+base_adj+7,
    f_etd_base,          etd_dt+base_adj+5,
    f_etd_60,            etd_dt+base_adj+60,
    f_eta_dest_base,     eta_dest+base_adj,
    f_ship_exp_45,       ship_dt+base_adj+45,
    f_rting_exp_10,      rting_port_eta+base_adj+10,
    f_transit_exp_10,    tran_port_eta+est_tran_days+base_adj+10,
    f_rting_exp_70,      rting_port_eta+base_adj+70,
    f_transit_exp_70,    tran_port_eta+est_tran_days+base_adj+70,
    f_ship_exp_105,      ship_dt+base_adj+105,
    f_etd_next_mth, EOMONTH(etd_dt,0)+1,
    IFS(
        NOT(valid_hdrs), mkary("ERR: Col Headers", "Header Mismatch"),
        OR(hasPaidDate, NOT(hasPrice)), mkary("", "Paid or No Price"),
        sale_type_Fresh,
        IFS(
            hasShipDate, mkary(f_fresh_ship, "Fr-Ship"),
            TRUE, mkary("", "Fr-NoShip")
        ),
        sale_type_Dm,
        IFS(
            crit_dt_Inv,
            IFS(
                AND(NOT(hasPaidDate), hasInvDate), mkary(f_invoice_base, "Dm-Inv-InvBase"),
                AND(NOT(hasInvDate), hasTitleDate), mkary(f_title_transf_base, "Dm-Inv-TitleBase"),
                YE_and_transit, mkary(f_transit_eta_base, "Dm-Inv-TransitYE"),
                no_title_has_rting, mkary(f_rting_port_base, "Dm-Inv-RtingPort"),
                rting_port_not_YE, mkary(f_rting_port_ext, "Dm-Inv-RoutingExt"),
                no_transit_has_ship, mkary(f_ship_fallback, "Dm-Inv-ShipFallback"),
                TRUE, mkary("", "Dm-Inv-NoMatch")
            ),
            crit_dt_Title,
            IFS(
                AND(NOT(hasPaidDate), hasTitleDate), mkary(f_title_transf_base, "Dm-Title-Primary"),
                YE_and_transit, mkary(f_transit_eta_base, "Dm-Title-TransitYE"),
                no_title_has_rting, mkary(f_rting_port_base, "Dm-Title-RtingPort"),
                rting_port_not_YE, mkary(f_rting_port_ext, "Dm-Title-RoutingExt"),
                no_transit_has_ship, mkary(f_ship_fallback, "Dm-Title-ShipFallback"),
                TRUE, mkary("", "Dm-Title-NoMatch")
            ),
            crit_dt_Deliv,
            IFS(
                AND(NOT(hasPaidDate), hasWBLDate), mkary(f_delivery_base, "Dm-Del-Primary"),
                AND(NOT(hasWBLDate), hasTitleDate), mkary(f_title_transf_base, "Dm-Del-TitleBase"),
                YE_and_transit, mkary(f_transit_eta_base, "Dm-Del-TransitYE"),
                no_title_has_rting, mkary(f_rting_port_base, "Dm-Del-RtingPort"),
                rting_port_not_YE, mkary(f_rting_port_ext, "Dm-Del-RoutingExt"),
                no_transit_has_ship, mkary(f_ship_fallback, "Dm-Del-ShipFallback"),
                TRUE, mkary("", "Dm-Del-NoMatch")
            ),
            crit_dt_RtingPrt,
            IFS(
                AND(NOT(hasPaidDate), hasRtingETA), mkary(f_rting_port_base, "Dm-Rting-Primary"),
                YE_and_transit, mkary(f_transit_eta_base, "Dm-Rting-TransitYE"),
                rting_port_not_YE, mkary(f_rting_port_ext, "Dm-Rting-Extended"),
                no_transit_has_ship, mkary(f_ship_fallback, "Dm-Rting-ShipFallback"),
                TRUE, mkary("", "Dm-Rting-NoMatch")
            ),
            crit_dt_CheckSO,
            mkary("", "Dm-CheckSO-IFS_Not_Impl"),
            days_to_add="Check SO", mkary("", "Dm-CheckSO-DaysAdd"),
            TRUE, mkary("ERR: Dom. logic fell thru", "Dm-Logic-Error")
        ),
        sale_type_Ex,
        IFS(
            OR(crit_dt_Inv, crit_dt_DDS),
            IFS(
                hasInvDate, mkary(f_invoice_base, "Ex-DDS-Primary"),
                hasETDDate, mkary(f_etd_base, "Ex-DDS-ETD"),
                YE_and_transit, mkary(f_transit_exp_10, "Ex-DDS-TransitYE"),
                rting_port_not_YE, mkary(f_rting_exp_10, "Ex-DDS-RtingPort"),
                hasShipDate, mkary(f_ship_exp_45, "Ex-DDS-Ship"),
                TRUE, mkary("", "Ex-DDS-NoMatch")
            ),
            crit_dt_ETA_K,
            IFS(
                hasETADest, mkary(f_eta_dest_base, "Ex-ETA-Primary"),
                hasETDDate, mkary(f_etd_60, "Ex-ETA-ETD"),
                YE_and_transit, mkary(f_transit_exp_70, "Ex-ETA-TransitYE"),
                rting_port_not_YE, mkary(f_rting_exp_70, "Ex-ETA-RtingPort"),
                hasShipDate, mkary(f_ship_exp_105, "Ex-ETA-Ship"),
                TRUE, mkary("", "Ex-ETA-NoMatch")
            ),
            crit_dt_ETD,
            IFS(
                hasETDDate, mkary(f_etd_next_mth, "Ex-ETD-Primary"),
                YE_and_transit, mkary(f_transit_exp_10, "Ex-ETD-TransitYE"),
                rting_port_not_YE, mkary(f_rting_exp_10, "Ex-ETD-RtingPort"),
                hasShipDate, mkary(f_ship_exp_45, "Ex-ETD-Ship"),
                TRUE, mkary("", "Ex-ETD-NoMatch")
            ),
            TRUE, mkary("", "Ex-UnknownCritDate")
        ),
        TRUE, mkary("", "Unknown-SaleType")
    )
)